### ISSUE TITLE
Jakiej licenziji mamy uzyc?

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#10]
Setup.py w sobie miesci MIT licenzje, a root projektu GNU GP 2. Jakie z tych dwoch powinnismy uzyc?

**Comment by StanczakDominik** [comment]
A, to mój błąd, przekopiowałem setup.py z innego mojego projektu, a tam użyłem MIT :D

Generalnie, za https://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code

> * Always license your code.  Unlicensed code is closed code, so any open license is better than none (but see #2).
> * Always use a GPL-compatible license. GPL-compatible licenses ensure broad compatibility for your code, and include GPL, new BSD, MIT, and others (but see #3).
> * Always use a permissive, BSD-style license. A permissive license such as new BSD or MIT is preferable to a copyleft license such as GPL or LGPL.

Gdzie to ostatnie wynika z tego, że jesteśmy bardziej w świecie naukowym niż czysto software'owym, a nauka ma być otwarta i dostępna dla wszystkich.

A czytając jeszcze https://opensource.stackexchange.com/a/582, byłbym za BSD 3-clause, czyli [taką jaką mamy na PlasmaPy](https://github.com/PlasmaPy/PlasmaPy/blob/master/LICENSE.md) :)

Ale jeśli masz silne poglądy na uprzednio wybrane GNU-GPL2, możemy o tym podebatować :)

**Comment by okmechak** [comment]
Solution in #37 
BSD 3-clause
