### ISSUE TITLE
Ogarnięcie githuba

### ISSUE THREAD

**Issue by StanczakDominik** [SocSIM/SocSIM#12]
@avocadit @amjankowska trzebaby się z tym ogarnąć :) myślę że wystarczy jeden z nas @okmechak (chyba że wolisz żebyśmy obaj tam byli?) i ze ~2 godzinki na githuba + użytkowe podstawy gita. W związku z tym, pytania:

1. pracujecie z Windowsa, Linuxa czy czegoś applowskiego? Od tego zależy co bym Wam sugerował doinstalować przed spotkaniem.
2. jakie terminy Wam pasują? Oleg, podaj swoje: dla mnie czwartek 11-15, ten piątek do 10, weekend i ten poniedziałek w razie potrzeby cały, wtorek do 14 i środa najchętniej jeśli już to wieczorem.

**Comment by okmechak** [comment]
Mi tak naprawde tez by bylo ciekawie dowiedziec sie czegos nowego i od ciebie ;) Sam korzystam z podstawowych mozliwosci githuba(push, pull, commit, add..) Ale ta jednej osoby starczy, ja moge w poniedzialek do 12.00 we wtorek od rana do 14.00

**Comment by avocadit** [comment]
Może można zrobić tak, że teraz z 1-2 tyg pobawimy się we własnym zakresie, a w okolicach drugiej konsultacji czwartkowej zrobimy spotkanie (może będą pytania i też miejsce na ciekawsze rzeczy, o których wspomniał Oleg).

**Comment by okmechak** [comment]
Na poczatku, jak zaczalem programowac, a jesczce nie dobrze kojarzylem git.. to tyle mi zmian poznikalo, a jeszcze wiecej emocji z tym bylo powiazane, tak ze polecam nie niedooceniac gita ;) 
@StanczakDominik czy wiesz resurs o gitcie do nauczania sie? 
Ja poprsotu korzystalem z oficialnej dokumentacji https://git-scm.com/doc, ale jest imho o wiele wieksza niz my potrzebujemy. 

Tez na przyklad Visual Code ma graficzny interface do korzystania z gitu, z czego ja i korzystam caly czas i polecam - tutaj jest o tym napisane https://code.visualstudio.com/docs/editor/versioncontrol.

**Comment by StanczakDominik** [comment]
> Na poczatku, jak zaczalem programowac, a jesczce nie dobrze kojarzylem git.. to tyle mi zmian poznikalo, a jeszcze wiecej emocji z tym bylo powiazane, tak ze polecam nie niedooceniac gita ;)

To jest prawda, git jest trochę dwusiecznym mieczem.

@avocadit IMHO - byłoby dla Was prościej pokazać co na początek warto o tym wiedzieć, żebyście nie zaczynali nagle uczyć się wszystkiego jak leci :)

> @StanczakDominik czy wiesz resurs o gitcie do nauczania sie?

Oficjalna dokumentacja jest dobra ale wyczerpuje zarówno temat jak i czytelnika :) Polskich materiałów znam mało, https://blog.udacity.com/2015/06/a-beginners-git-github-tutorial.html jest ok, ale głównie w moim przypadku - jakieś losowe tutoriale z netu i praktyka z kilku dobrych (żeby nie powiedzieć, git) lat.

Ewentualnie https://git-scm.com/book/en/v2 jest spoko

**Comment by StanczakDominik** [comment]
To tyle co jestem w stanie powiedzeić zanim zasnę

**Comment by avocadit** [comment]
@StanczakDominik, @amjankowska:  Jak Wam pasuje poniedziałek ok 1300? (mam zajęcia po 15tej)

**Comment by StanczakDominik** [comment]
Dla mnie spoczko

**Comment by okmechak** [comment]
Przyjaciel podpowiedzial tutorial na git w polskim jezyku ;P
https://github.com/jakubnabrdalik/gitkurwa/blob/master/configNSFW_PL

```
cotamkurwa = !sh -c 'git fetch' && git log --oneline HEAD..origin/$1
cotammistrzukurwa = !sh -c 'git fetch' && git log --oneline HEAD..origin/master
ktotamkurwa = !sh -c 'git shortlog HEAD..origin/$0'
ktotammistrzukurwa = !sh -c 'git shortlog HEAD..origin/master'
```

**Comment by avocadit** [comment]
Znacie może odpowiedź od @amjankowska?

**Comment by amjankowska** [comment]
Wybaczcie. Tak jak rozmawiałam z Olgiem, o 12:30 mam zajęcia więc mieliśmy się spotkać jutro o 11. Pasowałoby tez Wam wtedy?

**Comment by StanczakDominik** [comment]
Dla mnie git

**Comment by avocadit** [comment]
Ok.

**Comment by avocadit** [comment]
>     1. pracujecie z Windowsa, Linuxa czy czegoś applowskiego? Od tego zależy co bym Wam sugerował doinstalować przed spotkaniem.
linux

**Comment by okmechak** [comment]
Ok, zarezerwowalem sale:
>Potwierdzamy rezerwacje sali Salka PWN 5.
Termin rezerwacji to 28.10.2019 11:00-13:30
gdzies tam spotkamy sie(budynek B)

**Comment by StanczakDominik** [comment]
OK, tak po dzisiejszym, z rzeczy które pamiętam/mam zapisane (lista jest pewnie mniej kompletna niż powinna być):

* @avocadit chciałeś sposób na hasłowe logowanie z Linuxa bez wpisywania hasła co i raz - to czego zwykle używam to logowanie z kluczem SSH - przejedź przez https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
* @okmechak chciałeś więcej materiałów o stash i rebase - w tej chwili nic nie mam, ale jak mi się coś przypomni - dam znać
* @okmechak, jak poszedłeś, przemyśleliśmy sprawę i stwierdziliśmy że zrobienie githubowej organizacji SocSIM i taki globalny fork, na który wszyscy wrzucają kod tylko przez pull requesty, faktycznie będzie lepszym pomysłem niż pushowanie Tobie na mastera. Wtedy Ty też potencjalnie lepiej to przećwiczysz. Tym się zajmuję w tej chwili i pewnie będziecie teraz dostawali spam powiadomień mailowych. Za paręnaście minut podeślę, co powinniście zrobić żeby zaktualizować konfigurację.

**Comment by StanczakDominik** [comment]
OK, @okmechak, mógłbyś spróbować przenieść to repozytorium do SocSIM/SocSIM tak jak napisali w https://help.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account, a potem sforkować SocSIM/SocSIM do siebie, na okmechak/SocSIM?

**Comment by StanczakDominik** [comment]
Myślałem z początku, żeby sforkować okmechak/SocSIM tam, ale to by się wiązało z koniecznością ręcznego przenoszenia wszystkich issues.

**Comment by StanczakDominik** [comment]
Aktualizacja konfiguracji, gdy już przeniesiemy główne repozytorium:

```bash
git remote set-url upstream https://github.com/SocSIM/SocSIM.git
# lub w wersji SSH, głównie @avocadit 
git remote set-url upstream git@github.com:okmechak/SocSIM.git

git fetch upstream  # żeby sprawdzić, czy pykło
```

W wersji dla @okmechak :

```bash
git remote rename upstream origin    # gdy już sforkujesz z organizacji na konto osobiste
git remote add upstream  git@github.com:okmechak/SocSIM.git

git fetch upstream  # żeby sprawdzić, czy pykło
```

**Comment by okmechak** [comment]
Wlasnie na samym pocztatku, tez myslalem czy tworzyc organizacje, czy prywatnie miec ten repozytorium. Albo czy sa jakies ogolny "FUW" czy "FUW zespolowe projekty" organizacji etc..

Super dzis byl introduction :)

Coz, ten issue juz przezyw siebie, zamykam

**Comment by okmechak** [comment]
Bylo by jeszcze bardzo przydatne tez "Ogarniecie pythona/numpaja". Chociaz tak rozumiem, ten caly projekt bedzie takim zadaniem. Pracolalem nad #3 ale okzalo sie ze moj mozg jest bardzo przyzwyczajony do C++ :bowtie:
Na przyklad, potrzebowalem 2D `np.array` objektow typu `SandPile`:

```python
self.array = np.empty(shape, dtype = SandPile)
````
ale to tak nie dziala. Proponuja robic cos takie:
```python
vSandPile=np.vectorize(SandPile)
```
a potem:
```python
vSnadPile(np.zeros(shape))
```
Co zlamalo moj C++ mozg :dizzy_face:
I takie to.. :zzz:
