### ISSUE TITLE
"dobra referencja" z arxiv na przyszły tydzień

### ISSUE THREAD

**Issue by StanczakDominik** [SocSIM/SocSIM#15]
Przeglądamy https://arxiv.org/abs/1301.2918, Ola robi dogłębniejszy research :p

**Comment by amjankowska** [comment]
Autor dobrej referencji popełnił 400stronicowy doktorat na ten temat, polecam!
http://wwwf.imperial.ac.uk/~pruess/publications/thesis_final/thesis_book.pdf

**Comment by StanczakDominik** [comment]
@amjankowska to jest ta książka którą dzisiaj pokazywałaś? dopnijmy ją do https://github.com/SocSIM/SocSIM/edit/master/README.md :)

**Comment by amjankowska** [comment]
Nie, to jest jeszcze coś innego, jest na libgenie http://93.174.95.29/_ads/F7595E1E9FFC863A0D77117778C3E77C
