### ISSUE TITLE
Spotkanie 31.10.19

### ISSUE THREAD

**Issue by amjankowska** [SocSIM/SocSIM#19]
Wrzucam też tu, ponieważ podejrzewam problem z pocztą. 

Nie mogę zarezerwować PWN na 0800 ponieważ biblioteka z której pobieramy klucz otwiera się 0900.

Zaproponowałam salę 1.22, czekamy na potwierdzenie Profesora.

**Comment by okmechak** [comment]
Jeżeli co to wszystkie maily dotarły ;)

**Comment by amjankowska** [comment]
Dostałam powiadomienie, że adres @StanczakDominik  ma "permanent fatal problem" i wiadomość nie zostanie wysłana ze względu na złą reputację mojego IP (jestem w FUW open). xD
