### ISSUE TITLE
Jak ustalac wersje programu eg 0.0.1, 0.2.0, 0.2.1, 0.3.0 i td.

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#25]
Na ile wiem ostatnia literka z prawej strony zmienia sie prawie za kazdym pull request(jezeli chociaz by troche ona ma sensowne zmiany). Mozna by bylo tez powiazac druga literke(po srodku) z naszymi milestrounes. Co wy na to?

**Comment by StanczakDominik** [comment]
Ło matko, nie! Mnóstwo zmian (częste aktualizacje `setup.py`) na mało pożytku.

Sugerowałbym [semantic versioning!](https://semver.org/)

Na razie stoimy na czymś typu 0.0.1 jako że jesteśmy w bardzo wczesnej developerce.

Wersje "oficjalne" (z podbiciem numerka) wypuszczamy tylko wtedy, kiedy faktycznie mamy coś, z czego Nasi Użytkownicy, których jeszcze nie mamy ALE CO TAM, mogliby skorzystać.

Numerek składa się z MAJOR.MINOR.PATCH, gdzie, pokrótce

* PATCH zwiększa się gdy wypuszczamy bugfixa - kod po stronie użytkownika nie zmienia się między 0.0.1 a 0.0.2, poza tym że w 0.0.2 działałby bez buga
* MINOR zwiększa się, gdy dodajemy nową funkcjonalność bez kompatybilności wstecznej - wersja 0.1.0 nie psuje kodu napisanego na podstawie 0.0.1, ale funkcjonalności z 0.1.0 nie było w 0.0.1, więc nie będzie na niej działać bez aktualizacji
* MAJOR zwiększa się, gdy zmieniamy API, psujemy istniejący kod (np. printy między pythonem 2 a 3) i wymagamy żeby użytkownik się dopasował

**Comment by okmechak** [comment]
Tak wlasnie tez nie wiedzialem co zrobic z tymi czestymi zmianami kiedy one sa lokalnie. Ale dzieki za wielka odpowiedz i link. W takim razie proponuje zmieniac wersje za potrzeby, ale nie czesto, zeby te zmiany do wszytkich trafialy.

**Comment by StanczakDominik** [comment]
Zdefiniuj, do wszystkich? My jako twórcy projektu i tak powinniśmy pracować
z najbardziej aktualnej wersji na masterze - wersje releasowane to my, ale
nie nas :D

**Comment by okmechak** [comment]
Nie do konca zrozumialem :) 

Wychodzilem z zalozenia, ze nie zbyt czesto bede robic pull request. I wtedy moga byc konflikty u wersjach. Ale jezeli czesto robic pull request, to juz nie ma tego problemu. Czy jak?

**Comment by StanczakDominik** [comment]
OK, przepraszam za niejasną wiadomość. Miałem na myśli, że my jako twórcy i tak będziemy pracować nie na jakichś releasowanych wersjach, tylko aktualizując kod przez `git pull` - więc dla nas wersje są nieistotne.
