### ISSUE TITLE
Chat for codding issues

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#26]
Dodalem ten issue zeby komunikowac o roznych problemach w trakcie implementacji/kodowania w pythonie i td.

No i wlasnie mam taki problem, chcialem strworzyc metode drive_at_center()
zeby dodawac ziarenka poprsotu po centrum. ale nawet jak skomentowalem cale cialo fcji(mojej implementacji) to wciaz wyskakuje bled:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
 in 
----> 1 manna.drive_at_center(1)

c:\Users\ofcra\Dev\socsim\SOC\models\manna.py in drive_at_center(self, num_particles)
     38         """
     39         #x = self.L / 2
---> 40         #print(x)
     41         #y = x
     42         #print(type(x))

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

PS: anyway do zobaczenia jutrem i dobranoc..

**Comment by StanczakDominik** [comment]
OK, to będziesz mi musiał pokazać, czegoś takiego jeszcze nie widziałem :rofl:
