### ISSUE TITLE
Podział pracy z modelami

### ISSUE THREAD

**Issue by StanczakDominik** [SocSIM/SocSIM#29]
No dobra, to jak dzielimy się modelami do wstępnego podłubania na kolejny tydzień (czy za dwa, jak ustaliliście?)? Wypisuję tak, jak je pamiętam:

* [x] Abelowy Manna - jest, do ewentualnych niewielkich poprawek
* [x] Nieabelowy Manna - do łatwego przerobienia z istniejącego
* [ ] Abelowy BTW - komu, komu?
* [ ] Nieabelowy BTW - może być na tyle zbliżony do poprzedniego że jak już się zacznie jeden to pójdzie i drugi
* [ ] Forest fire
* [ ] chyba jednowymiarowy BTW?

Opcjonalnie:

* [ ] Istniejący avalanche @okmechak: nie pamiętam, który to możnaby go dopasować
* [ ] earthquake jak dla @avocadit niby mieliśmy przedyskutować następnym razem, ale IMO nie musiałoby wcale być trudno go zaimplementować...

W kwestii technikaliów, w większości istniejącą funkcjonalność będziemy mogli przekopiować z `manna.py` - jak zobaczymy, że coś duplikujemy, to się wstawi do klasy bazowej albo potem zrefactoruje - na razie miejmy coś co działa.

Ogólne porady - otwierajcie pull requesty wcześnie, pracujcie "publicznie", róbcie dużo małych commitów i w razie wątpliwości pytajcie resztę :)

**Comment by avocadit** [comment]
> (...) na kolejny tydzień (czy za dwa, jak ustaliliście?)

na kolejny

**Comment by avocadit** [comment]
Dzięki za wskazówki. Obecnie podłubałem nad nieabelową Manną i nad jednym z earthquake'owych modeli (OFC). Warto byłoby to jeszcze pomiętosić, sprawdzając bardziej sensowność lub nienaiwność.

**Comment by okmechak** [comment]
Ja by chcilem BTW

**Comment by StanczakDominik** [comment]
No dobra, @okmechak, zdążysz zacząć BTW do jutra (włącznie)?

@amjankowska spróbowałabyś zrobić forest fire na podstawie tych już istniejących?

Ew. ja mogę któryś z nich nastukać, albo spróbować zrobić ten jednowymiarowy BTW.

**Comment by amjankowska** [comment]
Spróbuję co się da z forest fire, ale nie spodziewajcie się gotowego modelu xD I'll do my best tho
