### ISSUE TITLE
Abelian/NonAbelian BTW sand pile model. Integrate into project structure

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#3]
- [x] Abelian
- [ ] nonAbelian
- [ ] jednowymairowy?

**Comment by okmechak** [comment]
Juz troche myle sie, ale czy BTW jest zrobiony? Jezeli nie, to do czwartku chcialem go zrobic.

**Comment by okmechak** [comment]
@amjankowska gdzie jest link, na ksiazke gdzie byly opisy do wszystkich modeli?
jakos wczesniej z niej opowiadalas na spotkaniu

**Comment by StanczakDominik** [comment]
>
> http://93.174.95.29/_ads/F7595E1E9FFC863A0D77117778C3E77C
>

Chyba to będzie to :)

>

**Comment by okmechak** [comment]
Chejka, czy mozecie mi pomoc..? pls :)
nie moge zrozumiec regul dla Abelian Sandpile..
tutaj na 91 stronie:
http://93.174.95.29/_ads/F7595E1E9FFC863A0D77117778C3E77C

**Comment by StanczakDominik** [comment]
![image](https://user-images.githubusercontent.com/11289391/70226038-68b90580-1750-11ea-92ab-c136e50ddc55.png)

To tak dla skonkretyzowania. Na szybko przejrzawszy, wydaje mi się że budujesz sobie dodatkową dużą macierz integerów o kształcie NxN (N = L^2, liczba pól na siatce), i ta macierz Ci mówi przy każdym topplingu: ok, toppluje się site n, to jest mój pierwszy indeks; teraz robię fora po wszystkich możliwych polach n' (pachnie mnożeniem macierzowym) żeby dowiedzieć się, ile na nie się toppluje.

Więc mamy toppling z każdego punktu powyżej wartości krytycznej na - potencjalnie - wszystkie punkty w siatce - które, to już zależy od tego, które elementy macierzy są niezerowe.

Macierz ma zerową główną przekątną, żeby uniknąć "samotopplingu", i niedodatnie elementy poza nią (bo de facto ta macierz mówi, ile znika z topplującego się pola; docelowe miejsca dostają minus tą wartość).

---

Tak ogółem, to to brzmi na strasznie złożone i memory intensive. Ja bym to, szczerze mówiąc, na razie olał i zrobił #43 jako najwyższy priorytet - ale nie dam rady przez parę najbliższych dni do tego usiąść i chciałbym, żeby ktoś to tymczasowo przejął.

**Comment by okmechak** [comment]
> i zrobił #43 jako najwyższy priorytet.

OK

**Comment by okmechak** [comment]
@StanczakDominik  polec pls inne zadanie mi, poprostu zostaniemy przy implementacji ktora juz jest.. to zbyt duze tracenie czasu na to

**Comment by StanczakDominik** [comment]
Dobra, to olewamy tą dziwną wersję. #44 teraz łatwo zrobić jak wykorzystasz `zarr.attrs` tak jak robię w świeżym PRze żeby zapisywać `save_every`. Test coverage nie rób, ja ogarnę na kolejne.
