### ISSUE TITLE
Nie dzialaja testy, pytest SOC -> No module named 'SOC'

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#36]
Probowalem odpalic test bedac w `./SocSIM`:
```
pytest SOC
```

ale dostaje blad:

>ImportError while importing test module 'C:\Users\ofcra\Dev\socsim\SOC\models\tests\test_btw.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
SOC\models\tests\test_btw.py:1: in <module>
    from SOC.models import BTW
E   ModuleNotFoundError: No module named 'SOC'
________________________________________ ERROR collecting SOC/models/tests/test_manna.py _________________________________________ 
ImportError while importing test module 'C:\Users\ofcra\Dev\socsim\SOC\models\tests\test_manna.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
SOC\models\tests\test_manna.py:1: in <module>
    from SOC.models import Manna
E   ModuleNotFoundError: No module named 'SOC'

**Comment by StanczakDominik** [comment]
W tym samym środowisku, z którego odpalasz testy, musisz puścić `python setup.py develop` żeby python widział nasz folder SOC jako importowalny pakiet

**Comment by okmechak** [comment]
Dziala! Dodalem to w readme
