### ISSUE TITLE
Earthquake model

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#4]
- [ ] wersja bardziej złożona, lubiana przez sejsmologów
- [ ] wersja druga, uproszczona, bez sprężynek (czysto grafowa)

**Comment by okmechak** [comment]
Ten model teraz jest w pull request?

**Comment by avocadit** [comment]
> Ten model teraz jest w pull request?

Taki był zamysł. OFC jako jeden z modeli earthquake'owych.

**Comment by StanczakDominik** [comment]
OK, mamy jedną zrobioną i coś z niej nawet wychodzi co wygląda jak trzęsienie ziemi (aktualne notebooki). Co teraz z tym? Wrzucamy drugi, czy olewamy na razie?

**Comment by avocadit** [comment]
> Co teraz z tym? Wrzucamy drugi, czy olewamy na razie?

Nie do końca wiem, o który chodzi w tym drugim pkcie. Może w miarę możliwości zrobi się crack model, dla porównania.

**Comment by StanczakDominik** [comment]
Ja to notowałem z nadzieją że będziesz wiedział ocb :D Dobra, to na razie myślę że można uznać za zrobione :)
