### ISSUE TITLE
Integracja loggera do kodu

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#41]
W ReadMe.md na samym poczatku robilem statement zeby korzystac z loggera, 
wlasnie zastanawiam sie jak sporo go dodac, czy tylko na wejsciu do f-cji, czy jakos wiecej?

```python
import logger

def handle_request(request):
    logger.info('Handling request %s', request)
    ....
```

czy poprostu zabrac statement z ReadMe.md 😄

**Comment by StanczakDominik** [comment]
szczerze mówiąc to ja jeszcze nigdy nie miałem sytuacji, gdzie faktycznie korzystałbym z logów :( raczej wolę jak mi ktoś przeklei wyjątek i reproducing example, a potem już sobie mogę hasać debuggerem po kodzie i patrzeć co się sypie.

Jak dla mnie możemy usunąć z readme póki nie będzie potrzeby go faktycznie używać :)

**Comment by okmechak** [comment]
> możemy usunąć z readme

done :)
