### ISSUE TITLE
Wyciągnąć wykładniki z histogramów

### ISSUE THREAD

**Issue by StanczakDominik** [SocSIM/SocSIM#43]
- [x] poprawić binowanie w histogramach
	- [ ] czy potrzebujemy większych, a zatem i szybszych, symulacji?
- [x] znaleźć liniowy fragment wykresu log-log
	- [x] czy istnieją gotowe rozwiązania na coś takiego? trochę nie wierzę że ich nie ma
	- [x] cutoff jako parametr do minimalizacji? wtedy mielibyśmy cztery, A+Bx, Size_dolny, Size_gorny
- [ ] zczytać parametry, porównać z analitycznymi dla Manny i chyba BTW? 
- [ ] radość

**Comment by avocadit** [comment]
Na spotkaniu było na podstawie Dobrej Referencji, ale wklejam dla porządku:
![20191128_091945](https://user-images.githubusercontent.com/56771919/69817191-57c13f00-11fa-11ea-974c-a13659b9b689.jpg)

**Comment by okmechak** [comment]
> zczytać parametry, porównać z analitycznymi dla Manny i chyba BTW
tego w tej chwili brakuje?
tak rozumiem, ze trzeba log-log mamy.. teraz dopiero trzeba dopasowac rownanie linii?

**Comment by StanczakDominik** [comment]
Równanie linii mamy, patrz - otwarty PR, tylko mam tam jakieś bugi i wartości są bez sensu :(

**Comment by StanczakDominik** [comment]
#45 to domknie; zamykam
