### ISSUE TITLE
Termin spotkania 5

### ISSUE THREAD

**Issue by avocadit** [SocSIM/SocSIM#46]
Na koniec spotk. 4 ustaliliśmy, że będzie mail z propozycjami. Rozesłany był niedawno. Jaki termin Wam pasuje?

**Comment by avocadit** [comment]
Mi np. poniedziałkowy (12/09) o 13tej.

**Comment by okmechak** [comment]
termin czego? nie do konca rozumiem

**Comment by avocadit** [comment]
Termin najbliższego spotkania.

**Comment by okmechak** [comment]
poniedzialek - 9.00 - 12.00
wtorek - 9.00 - 16.00
sroda - 13.00 - 18.00
czwartek - 9.00 - 11.00
piatek - 11.00 - 18.00

**Comment by StanczakDominik** [comment]
Profesor sugerował poniedziałek 9-14, lub środę po 15. Poniedziałek 9-14 dla mnie jest ok (chętniej później spośród tych, bo mam na 14 zajęcia, ale mogę pobibliotekować); w środę pracuję i prawdopodobnie będę padnięty, ale możemy spróbować.

@amjankowska, czwarty głos w dyskusji?

**Comment by okmechak** [comment]
Czy może ktoś by chciał jutro razem poprogramować na FUWie?

**Comment by StanczakDominik** [comment]
Chciał to zawsze, z "mógł" jest gorzej :(

**Comment by avocadit** [comment]
> Czy może ktoś by chciał jutro razem poprogramować na FUWie?

U mnie jutro zajęcia od 0930 do 1630.

**Comment by avocadit** [comment]
To może spotkanie w pn 11?

**Comment by okmechak** [comment]
> To może spotkanie w pn 11?

Tak, może być

**Comment by StanczakDominik** [comment]
Dla mnie git

**Comment by avocadit** [comment]
To po południu wyślę p. profesorowi propozycję.

**Comment by avocadit** [comment]
Profesor zgodził się na pn. (12/09) o 11tej. Prosił o przekazanie, co niniejszym, @okmechak @StanczakDominik @amjankowska, czynię. :)

**Comment by avocadit** [comment]
Jesteśmy w sali 1.22.
