### ISSUE TITLE
Forest fire model

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#5]
- [ ] wersja z podtrzymywanyn ogniem
- [ ] bardziej fizyczna wersja z piorunami i szybkim gaśnięciem

**Comment by avocadit** [comment]
https://github.com/jjasont/forest-fire-PH4505

**Comment by StanczakDominik** [comment]
@amjankowska wrzuciłabyś na GH to co masz do tej pory? doszlifujemy wspólnie :)
