### ISSUE TITLE
Lepsza metoda `run` w `SOC.common.simulation`

### ISSUE THREAD

**Issue by StanczakDominik** [SocSIM/SocSIM#51]
* [ ] skalowanie liczby iteracji przez L^2, żeby argumentem faktycznym była liczba cząstek na oczko siatki
* [ ] Obcinanie początkowych danych przed zaczęciem zbierania danych statystycznych; żeby układ miał czas na dojście do jako-takiej równowagi (po prostu kolejny parametr np. `wait_for_n_iters`
	* można wciąż zbierać snapshoty do animacji

**Comment by amjankowska** [comment]
>skalowanie liczby iteracji przez L^2, żeby argumentem faktycznym była liczba cząstek na oczko siatki

chodzi o to zeby metoda drive wrzucała density czastek?

**Comment by amjankowska** [comment]
![C55055C0-B770-45A8-A5AA-FBF1C643ED7B](https://user-images.githubusercontent.com/56721271/71118401-58853980-21d8-11ea-8d91-39ad43372731.jpeg)

**Comment by StanczakDominik** [comment]
Całą pętlę w drive trzeba będzie przełożyć na numbę w podobnym myku jak teraz jest toppling

Myślę że

**Comment by StanczakDominik** [comment]
Myślę że to był misclick

Trzeba ją zdefiniować od razu w Simulation.py bo jest wspólna dla manny i btw; ofc niech sobie po prostu przeciąży własną króciutką

**Comment by StanczakDominik** [comment]
HALT, NIE, ŹLE
nie możemy robić dużo iteracji w pętli w drive!

Pomyslcie o kolejności
100 ziarenek i dopiero jeden toppling

To nie to samo co 100 krotnie ziarenko i próba topplingu po każdym

Chyba to psuje wypłaszcza wykres w btw!!!!

Trzeba jednak modyfikować liczbę iteracji pętli w run, a liczby driveów nie ruszać
