### ISSUE TITLE
Spotkanie styczeń

### ISSUE THREAD

**Issue by amjankowska** [SocSIM/SocSIM#66]
Panowie, pamiętam że jutro, ale ktoś wie o której godzinie? Nie zapisałam :< @okmechak @avocadit  będziecie? @StanczakDominik  Ty chyba w pracy?

**Comment by StanczakDominik** [comment]
Tak, ja w pracy. Nie jestem przekonany że w ogóle ustaliliśmy tą godzinę.

**Comment by avocadit** [comment]
Zapisałem, że na 11tą.

**Comment by avocadit** [comment]
Nie udało mi się zrobić co zaplanowałem na dzisiaj, tzn. znalezienie czemu ofc nie daje sensowniejszego wykładnika. Muszę dokładniej zapoznać się z działaniem zarr'a. Będziecie mieli jakieś nowe rzeczy na spotkaniu?

**Comment by avocadit** [comment]
Jak @okmechak byłby, to bym go wypytał o zarr'a, bo już go zna.:)

**Comment by amjankowska** [comment]
Olga nie będzie, ja nie mam nic sensownego. Pracowałam nad tym moim, ale przyznaję bez bicia że potrzebuję pomocy żeby to jakoś scalić, bo FF jest kompletnie innym modelem. Chyba dziś pogadamy krótko z profesorem :p

**Comment by amjankowska** [comment]
Za to proponuję jakieś spotkanie nasze w czwórkę później w tym tygodniu. Może czwartek? (Zajęcia z poniedziałku wtedy) albo weekend

**Comment by avocadit** [comment]
Ja w czw mam zajęcia po 15tej. Wcześniej mogę o dowolnej porze.

**Comment by amjankowska** [comment]
@StanczakDominik @avocadit @okmechak jutro o 10 się widzimy. Tylko nie mogę zarezerwować pwn bo mam zablokowane konto biblioteczne, mógłby któryś z Was to zrobić?

**Comment by StanczakDominik** [comment]
Pisałem na riocie że ja jutro jednak się nie wyrobię :(

>
