### ISSUE TITLE
Kolejne spotkanie

### ISSUE THREAD

**Issue by StanczakDominik** [SocSIM/SocSIM#71]
Od poniedziałku 27 stycznia

**Comment by avocadit** [comment]
Jak widzicie piątek albo poniedziałek?:)

**Comment by okmechak** [comment]
Mi pasuje

**Comment by StanczakDominik** [comment]
No to jeśli wszystkim leży, poniedziałek, bo praca :(

**Comment by StanczakDominik** [comment]
BTW @avocadit na Riocie (ekhm ;) ) powstał plan żeby w czwartek spotkać się na uczelni i doprogramować tyle ile się da. Wtedy w poniedziałek potencjalnie możnaby nawet domknąć projekt. Wchodzisz w to?

**Comment by avocadit** [comment]
Tak. Na którą godz. we czw.?

**Comment by okmechak** [comment]
15.15 mam prezentacje, a wcześniej wszystko pasuje
