### ISSUE TITLE
Zrobic research na rachunek inych modeli, ktore wykazuja zachowanie SoC

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#9]
W tej chwili, znamy ze sa nastepne modele: SandPile, Earth-Quake i Forest-Fire, na rachunek innych modeli niczego nie wiadomo, w czym i polega problem.  

DoD
 - Lista z aktualnymi modelami(linki na artykuly) i cih opisem
 - Opis algorytmu ich dzialania.

**Comment by avocadit** [comment]
[The average avalanche size in the Manna Model and other models of self-organised criticality](https://arxiv.org/abs/1208.2069)

**Comment by okmechak** [comment]
@amjankowska  czy te zadanie mozna uwazac juz zrobionym?
Bo chyba juz mamy refki na sporo roznych modeli..

**Comment by StanczakDominik** [comment]
Myślę że na razie można :)
